# Generated by Django 5.0.6 on 2024-06-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_skill_users'),
        ('users', '0002_alter_myuser_age_alter_myuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='skills',
            field=models.ManyToManyField(related_name='users', to='main.skill'),
        ),
    ]
